steps:
  # Build the binary
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'main', 'main.go']
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/qwiklabs-gcp-01-4fc35229c6d2/my-repository/hello-cloudbuild-dev:',
      '.'
    ]
    id: Build

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/qwiklabs-gcp-01-4fc35229c6d2/my-repository/hello-cloudbuild-dev:'
    ]
    id: Push

  # Update the k8s deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set', 'image',
      'deployment/hello-cloudbuild',
      'hello-cloudbuild=us-central1-docker.pkg.dev/qwiklabs-gcp-01-4fc35229c6d2/my-repository/hello-cloudbuild-dev:'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

# Store images in Artifact Registry
images: [
  'us-central1-docker.pkg.dev/qwiklabs-gcp-01-4fc35229c6d2/my-repository/hello-cloudbuild-dev:'
]

# Use substitutions for project ID and tag
substitutions:
  _TAG_NAME: v1.0

# Cloud Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Use the default substitution variables
# qwiklabs-gcp-01-4fc35229c6d2 is automatically available in Cloud Build
